config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get 'search' => 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    # あるユーザーがフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
    get :followers, on: :member
    # あるユーザーをフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def join
    @group = Group.find(params[:group_id])
    @group.users << current_user
    redirect_to groups_path
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edti
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.users.delete(current_user)
    redirect_to groups_path
  end
  
  def new_mail
    @group = Group.find(params[:group_id])
  end
  
  def send_mail
    @group = Group.find(params[:group_id])
    group_users = @group.users
    @mail_title = params[:mail_title]
    @mail_content = params[:mail_content]
    ContactMailer.send_mail(@mail_title, @mail_content,group_users).deliver
  end


  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @group, method: :patch, local:true do |f| %>
        <% if @group.errors.any? %>
          <%= @group.errors.count %>error
            <ul>
              <% @group.errors.messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

        <h2>Group Create</h2>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, rows:'5', class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.file_field :image, class: "form-control-file", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.submit "Group Create", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー数</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= image_tag group.get_image, size:"40x40" %></td>
              <td>
                <%= link_to group_path(group) do %>
                  <%= group.name %>
                <% end %>
              </td>
              <td><%= group.introduction %></td>
              <td><i class="fas fa-user"></i>　<%= group.users.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <%= form_with model: @group, local:true do |f| %>
        <% if @group.errors.any? %>
          <%= @group.errors.count %>error
            <ul>
              <% @group.errors.messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

        <h2>Group Create</h2>
        <div class="form-group">
          <%= f.label :グループ名 %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :紹介文 %>
          <%= f.text_area :introduction, rows:'5', class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :グループ画像 %>
          <%= f.file_field :image, class: "form-control-file", accept: 'image/*' %>
        </div>
        <div class="form-group">
          <%= f.submit "Group Create", class: "btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/new_mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Event Mail</h2>
      <%= form_with url: group_send_mail_path(@group),method: :get, local: true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :mail_title,class:'form-control'%>
        </div>
        <div class="form-group">
            <%=f.label:content %>
            <%= f.text_area :mail_content,class:'form-control' %>
        </div>
        <div>
          <%= f.submit'送信', class:"btn btn-info" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/groups/send_mail.html.erb
<div class="container">
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h3 class="margin_top text-center">送信が完了しました</h3>
        <div class="margin_top">内容は以下の通りです。</div>
          <div class="small_margin_top">
            [タイトル]<p class="font-weight-bold"> <%= @mail_title %></p>
          </div>
          <div>
            [本文]<p class="font-weight-bold"> <%= safe_join(@mail_content.split("\n"),tag(:br)) %></p>
          </div>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Groups</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_image, size:"40x40" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% @group.users.each do |member| %>
                • <%= member.name %><br>
              <% end %>
            </td>
            <% if @group.owner_id == current_user.id %>
              <td><%= link_to "Edit", edit_group_path(@group), class:"btn btn-success" %></td>
              <td><%= link_to "Notice an Event", group_new_mail_path(@group), class:"btn btn-info" %></td>
            <% elsif @group.users.include?(current_user) %>
              <td><%= link_to "Leave this Group", group_path(@group), method: :delete, class:"btn btn-sm btn-danger" %></td>
            <% else %>
              <td><%= link_to "Join this Group", group_join_path(@group), class:"btn btn-sm btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>