config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root :to =>"homes#top"
  get "home/about"=>"homes#about"
  get 'search' => 'searches#search'

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    # あるユーザーがフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
    get :followers, on: :member
    # あるユーザーをフォローしている人を表示させるルーティング。on: :memberでidを含ませることができる
  end
  
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]

  resources :groups do
    get "join" => "groups#join"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  # favorited_usersというモデルは存在しないので、favoritesモデルを介してuserモデルのデータを持ってくる
  has_many :book_comments, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(searches,words)
    if searches == "perfect_match"
      @book = Book.where("title LIKE(?) OR body LIKE(?)", "#{words}", "#{words}")
    elsif searches == "forward_match"
      @book = Book.where("title LIKE(?) OR body LIKE(?)", "#{words}%", "#{words}%")
    elsif searches == "backward_match"
      @book = Book.where("title LIKE(?) OR body LIKE(?)", "%#{words}", "%#{words}")
    elsif searches == "partial_match"
      @book = Book.where("title LIKE(?) OR body LIKE(?)", "%#{words}%", "%#{words}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users
  
  validates :name, presence: true
  validates :introduction, presence: true
  has_one_attached :image
  
  def get_image
    (image.attached?) ? image : 'no_image.jpg'
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  
  validates :message, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :users, through: :rooms
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower
  # あるユーザーがフォローしている人をrelationshipsテーブルを介して取ってくる
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following
  # あるユーザーをフォローしている人をrelationshipテーブルを介して取ってくる
  has_many :group_users
  has_many :groups, through: :group_users

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries

  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def is_followed_by?(user)
    # 引数に渡されたユーザーにフォローされているかどうかの判定をする
    reverse_of_relationships.find_by(following_id: user.id).present?
    # reverse_of_relationshipsはfollowerを指している。
    # following_id: user.idでuseridをfollowingに代入
  end

  def self.looks(searches,words)
    if searches == "perfect_match"
      @user = User.where("name LIKE ?", "#{words}")
    elsif searches == "forward_match"
      @user = User.where("name LIKE ?", "#{words}%")
    elsif searches == "backward_match"
      @user = User.where("name LIKE ?", "%#{words}")
    elsif searches == "partial_match"
      @user = User.where("name LIKE ?", "%#{words}%")
    else
      @user = User.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @book_comment = BookComment.new
  end

  def index
    to = Time.current.at_end_of_day
    # config/application.rbに設定してあるタイムゾーンを元に現在日時を取得
    # 要は現在の時刻をとってきている
    # at_end_of_dayは1日の終わりを23:59に設定している
    from = (to - 6.day).at_beginning_of_day
    # (to - 6.day)は上記記述のtoに入っている時刻から前６日間
    # at_beginning_of_dayは時刻を1日の始まりの0:00に設定

    # 上記コードを要約すると
    # 6日前の0:00から今日の23:59までのデータを取ってくるという意味になる
    @books = Book.includes(:favorited_users).
    # bookモデルからデータを取得するときにfavorited_usersのデータもまとめて取得する
    # Book.allでも全データ取り出せるが、都度どのユーザーが投稿したのか取りに行かないといけない
    # includesを書くことでfavorited_usersテーブルのデータを事前に読み込まれているため無駄にSQL文が発行されない
      # sort {|a,b|
      # sortメソッドは降順、昇順の並び替えをするメソッド
      # 普通にsortすると2よりも10,11の方が小さいと判定されてしまうのでブロック|a,b|を渡してあげる
        # a.favorited_users.includes(:favorites).where(created_at: from...to).size <=>
        # b.favorited_users.includes(:favorites).where(created_at: from...to).size
        # a,b両辺(aが左辺,bが右辺)の値を比較していいね数を並び替えている
      # }.reverse

      sort_by {|x|
        x.favorited_users.includes(:favorites).where(created_at: from...to).size
      }.reverse
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # ログインしているidを投稿するユーザのidに入れてあげないと投稿している人が誰かわからなくなる
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    @user = User.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def entry_params
    params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <% if book.errors.any? %>
  <%= book.errors.count %>error
    <ul>
      <% book.errors.messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td class="favorite_btn_<%= book.id %>"><%= render 'favorites/favorite', book: book %></td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"100x100" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>

          <td class="favorite_btn_<%= @book.id %>"><%= render 'favorites/favorite', book: @book %></td>

          <td class="comment_count"><%= render 'book_comments/comment_count', book: @book %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>

      <table class="comment_index"><%= render 'book_comments/comment', book: @book %></table>

      <%= form_with model:[@book, @book_comment], url:book_book_comments_path(@book), method: :post, local:false do |f| %>
        <%= f.text_area :comment, rows:'5', class:"w-100" %>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="left-button">
  <%= link_to "ユーザー一覧に戻る", users_path, class:"edit-link" %>
</div>
<h4 class="rooms-title"><%= @user.name %>さんとのチャット</h4>
<% @entries.each do |e| %>
  <div class="user-name">
    <strong>
      <%= link_to user_path(@user) do %>
        <%= image_tag e.user.get_profile_image, size:"40x40" %>
        <%= e.user.name %>
      <% end %>
    </strong>
  </div>
  <hr>
  <div class="chats">
    <div class="chat">
      <% if @messages.present? %>
        <% @messages.each do |m| %>
          <div class="chat-box">
            <div class="chat-face">
              <%= image_tag m.user.get_profile_image, size:"40x40" %>
            </div>
            <div class="chat-hukidashi">
              <strong><%= m.message %></strong><br>
              <%= m.created_at.strftime("%Y-%m-%d %H:%M") %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="posts">
      <%= form_with model:@message do |f| %>
        <%= f.text_field :message, placeholder: "メッセージを入力して下さい", size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "投稿", class:"form-submit" %>
      <% end %>
    </div>
  </div>
<% end %>